<script setup lang="ts">
import { useTicketsStore } from '@/stores/tickets';
import type { Category, Ticket } from '@/types/api'
import { ref, watch } from 'vue'
import { formatAgoFromDate } from '@/utils/time';
import CatDot from '../CatDot.vue';


const {ticket, category} = defineProps<{
  ticket: Ticket,
  category: Category | null
}>()

const tickets = useTicketsStore()

// ── Title + summary editing ──────────────────────────────────────────────────
// Both fields are AI-generated by default but operator-editable. Edits are
// optimistic via the store; a small "edited" pill + reset button surfaces the
// override. Empty string on PATCH clears it server-side (next sync regenerates).
const titleDraft = ref('')
const summaryDraft = ref('')
const titleEditing = ref(false)
const titleSaving = ref(false)
const summaryEditing = ref(false)
const summarySaving = ref(false)
const editError = ref<string | null>(null);

watch(
  () => ticket.id,
  () => {
    titleDraft.value = ticket.title ?? '';
    summaryDraft.value = ticket.summary ?? '';
    titleEditing.value = false;
    summaryEditing.value = false;
    editError.value = null;
  },
  { immediate: true }
)

async function saveTitle() {
  const id = ticket?.id;
  if (!id) return;
  const next = titleDraft.value.trim();
  if (next === (ticket?.title ?? '')) {
    titleEditing.value = false;
    return;
  }
  titleSaving.value = true;
  editError.value = null;
  try {
    await tickets.editTicket(id, { title: next });
    titleEditing.value = false;
  } catch (e) {
    editError.value = (e as Error).message;
  } finally {
    titleSaving.value = false;
  }
}
async function saveSummary() {
  const id = ticket.id;
  if (!id) return;
  const next = summaryDraft.value.trim();
  if (next === (ticket.summary ?? '')) {
    summaryEditing.value = false;
    return;
  }
  summarySaving.value = true;
  editError.value = null;
  try {
    await tickets.editTicket(id, { summary: next });
    summaryEditing.value = false;
  } catch (e) {
    editError.value = (e as Error).message;
  } finally {
    summarySaving.value = false;
  }
}

/** Clear the operator override server-side; next sync restores AI value. */
async function resetField(field: 'title' | 'summary') {
  const id = ticket.id;
  if (!id) return;
  editError.value = null;
  try {
    await tickets.editTicket(id, { [field]: '' });
    if (field === 'title') {
      titleDraft.value = ticket.title ?? '';
      titleEditing.value = false;
    } else {
      summaryDraft.value = ticket.summary ?? '';
      summaryEditing.value = false;
    }
  } catch (e) {
    editError.value = (e as Error).message;
  }
}

/** Cancel editing */
function cancelEdit(field: 'title' | 'summary') {
  if (field === 'title') {
    titleDraft.value = ticket.title ?? '';
    titleEditing.value = false;
  } else {
    summaryDraft.value = ticket.summary ?? '';
    summaryEditing.value = false;
  }
}

</script>

<template>
  <div class="title-row">
    <input
    v-if="titleEditing"
    v-model="titleDraft"
    class="title-input" type="text" maxlength="200"
    placeholder="Subject…"
    :disabled="titleSaving"
    @keydown.enter.prevent="saveTitle"
    @keydown.esc.prevent="() => { cancelEdit('title'); }"
    @blur="saveTitle" />
    <h2 v-else class="title" :class="{ placeholder: !ticket.title }" @click="titleEditing = true">
      {{ ticket.title || 'Add subject…' }}
    </h2>
    <span v-if="ticket.title_user_edited && !titleEditing" class="edited-pill" title="Operator-edited">edited</span>
    <button
v-if="ticket.title_user_edited && !titleEditing" class="reset" title="Reset to AI-generated subject"
      @click="resetField('title')">
      ↺
    </button>
  </div>

  <div class="row">
    <CatDot v-if="category" :color="category.color" :size="9" />
    <span class="mono cat">{{ category?.name ?? 'Uncategorized' }}</span>
    <span class="mono dim">{{ formatAgoFromDate(ticket.updated_at) }}</span>
  </div>

  <!-- Editable summary. Click to expand to textarea. -->
  <div class="summary-row">
    <textarea
v-if="summaryEditing" v-model="summaryDraft" class="summary-input" maxlength="600" rows="4"
      placeholder="Add a description…" :disabled="summarySaving" @keydown.esc.prevent="() => { cancelEdit('summary'); }" @blur="saveSummary" />
    <p v-else class="summary" :class="{ placeholder: !ticket.summary }" @click="summaryEditing = true">
      {{ ticket.summary || 'Add a description…' }}
    </p>
    <div v-if="ticket.summary_user_edited && !summaryEditing" class="edit-meta">
      <span class="edited-pill" title="Operator-edited">edited</span>
      <button class="reset" title="Reset to AI-generated summary" @click="resetField('summary')">
        ↺
      </button>
    </div>
  </div>

  <div v-if="editError" class="mono err">{{ editError }}</div>

  <div class="row">
    <span class="customer">{{ ticket.author.name ?? '—' }}</span>
    <a v-if="ticket.url" class="mono link" :href="ticket.url" target="_blank" rel="noopener">
      Open in Intercom ↗
    </a>
  </div>
</template>

<style scoped>
.title-row {
  display: flex;
  align-items: flex-start;
  gap: 6px;
}
.title {
  margin: 0;
  font-size: 15px;
  font-weight: 600;
  line-height: 1.35;
  color: var(--ink);
  cursor: text;
  flex: 1;
  min-width: 0;
}
.title.placeholder {
  color: var(--ink-3);
  font-weight: 500;
  font-style: italic;
}
.title:hover {
  background: var(--hover);
  border-radius: 4px;
  margin: -2px -4px;
  padding: 2px 4px;
}
.title-input {
  flex: 1;
  font-family: var(--font-sans);
  font-size: 15px;
  font-weight: 600;
  line-height: 1.35;
  color: var(--ink);
  padding: 2px 4px;
  border: var(--hairline) solid var(--accent);
  border-radius: 4px;
  background: var(--panel);
}
.summary {
  margin: 0;
  font-size: 12.5px;
  line-height: 1.5;
  color: var(--ink-2);
}
.customer {
  font-size: 12px;
  color: var(--ink);
}
.summary-row {
  display: flex;
  gap: 6px;
  align-items: flex-start;
}
.summary-input {
  flex: 1;
  font-family: var(--font-sans);
  font-size: 12.5px;
  line-height: 1.5;
  color: var(--ink);
  padding: 6px 8px;
  border: var(--hairline) solid var(--accent);
  border-radius: var(--radius-chip);
  background: var(--panel);
  resize: vertical;
}
.summary.placeholder {
  color: var(--ink-3);
  font-style: italic;
}
.edit-meta {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 4px;
}
.edited-pill {
  font-family: var(--font-mono);
  font-size: 8.5px;
  letter-spacing: 0.05em;
  text-transform: uppercase;
  color: var(--ink-3);
  background: var(--chip-bg);
  border: var(--hairline) solid var(--line);
  border-radius: var(--radius-chip);
  padding: 1px 5px;
  white-space: nowrap;
  align-self: flex-start;
}
.reset {
  font-family: var(--font-mono);
  font-size: 11px;
  background: transparent;
  border: 0;
  color: var(--ink-3);
  cursor: pointer;
  padding: 2px 4px;
  border-radius: 4px;
}
.reset:hover {
  color: var(--accent);
  background: var(--hover);
}
.row {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}
.link {
  margin-left: auto;
  color: var(--accent);
  text-decoration: none;
}

</style>
