"""Add ticket_embeddings vec0 virtual table.

Roadmap 2.4 — local embedding layer (keystone). Stores one 384-dim embedding
per ticket (all-MiniLM-L6-v2), computed best-effort on ingest from the
customer-visible `parts[]` plus the operator's local note ONLY. Intercom
internal notes are never embedded (cross-package invariant #4).

This is a SEPARATE store from `ai_cache` — writing an embedding never touches
the AI cache or the content signature (invariant #6).

A `vec0` virtual table cannot be autogenerated from `Base.metadata`, so it is
created with hand-written DDL via `op.execute`. The sqlite-vec extension is
loaded per-connection (see `app/models.py:_load_sqlite_vec`), so the CREATE
VIRTUAL TABLE statement resolves the `vec0` module at migration time — including
the in-memory test DB, whose connection loads the extension via the same hook.

SQLite-only: the `vec0` module has no Postgres analogue. Guarded on the bind
dialect so the (currently unused) Postgres path is unaffected.

Revision ID: 0014
Revises: 0013
Create Date: 2026-05-27 00:00:14.000000 UTC
"""

from __future__ import annotations

from alembic import op

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None

# all-MiniLM-L6-v2 produces 384-dimensional sentence embeddings.
EMBEDDING_DIM = 384


def upgrade() -> None:
    if op.get_bind().dialect.name != "sqlite":
        return
    # `ticket_id` is an auxiliary (metadata) column on the vec0 table, keyed
    # 1:1 to tickets.id. `embedding` is the float32 vector column.
    op.execute(
        "CREATE VIRTUAL TABLE ticket_embeddings USING vec0("
        "ticket_id TEXT PRIMARY KEY, "
        f"embedding FLOAT[{EMBEDDING_DIM}]"
        ")"
    )


def downgrade() -> None:
    if op.get_bind().dialect.name != "sqlite":
        return
    op.execute("DROP TABLE IF EXISTS ticket_embeddings")
